public class TweetClass {
    public String content;
    public String author;

    TweetClass(String msg, String name){
        content = msg;
        author = name;
    }

    public String displayTweet(){
        return content;
    }

    public Boolean contains(String s){
        return content.contains(s);
    }

    public static void main(String[] args) {
        TweetClass test = new TweetClass("It is now possible to learn about a person's mobility preferences from data generated by their smartphone",
                "Tim");
        System.out.println(test.displayTweet());
    }
}
